name: build windows container

on: workflow_dispatch

env:
  D_REGISTRY: ghcr.io
  D_PROJECT: erezgeva

jobs:
  container:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: log in to the container registry
      if: ${{ github.actor == github.repository_owner }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.D_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      if: ${{ github.actor == github.repository_owner }}
      run: |
        echo "D_REGISTRY=$D_REGISTRY"
        echo "D_PROJECT=$D_PROJECT"
        docker build -t ghcr.io/erezgeva/win .
        docker push ghcr.io/erezgeva/win
#       docker build -t $D_REGISTRY/$D_PROJECT/win:latest .
#       docker push $D_REGISTRY/$D_PROJECT/win:latest
